package tools

import (
	"encoding/json"
	"fmt"
	"os"
	"path/filepath"
	"strings"

	"github.com/BurntSushi/toml"
	"github.com/everyapi-ai/everyapi-sdk/config"
)

type codexUserDefaults struct {
	Model                string `toml:"model"`
	ModelReasoningEffort string `toml:"model_reasoning_effort"`
}

// prepareCodex generates an isolated CODEX_HOME under
// ~/.config/everyapi/codex-home and seeds it with the two files codex
// reads on startup:
//
//   - auth.json  →  pins auth_mode to "apikey" and stamps the relay
//     key, so codex skips its ChatGPT device-login dance even when
//     the user's real ~/.codex/auth.json is in chatgpt mode.
//   - config.toml → defines an `everyapi` model_provider pointing at
//     <apiBase>/v1 (wire_api = "responses" — the gateway exposes the
//     full /v1/responses surface, see backend/internal/router/relay
//     -router.go) and selects it as the default model_provider. Codex
//     does NOT read OPENAI_BASE_URL on its own; this is how requests
//     actually get routed through EveryAPI.
//
// The directory is reused across runs (sessions, cache, history
// accumulate per spec — user explicitly opted into a session-isolated
// EveryAPI codex environment, but losing them on every launch would be
// gratuitous). auth.json and EveryAPI-owned config.toml fields are rewritten
// every call so a fresh relay key always wins. User-selected model defaults
// are preserved.
//
// Returns the env additions to overlay on top of envFn — primarily
// CODEX_HOME so codex sees our config dir instead of ~/.codex.
func prepareCodex(apiBase, token string) (map[string]string, error) {
	cfgDir, err := config.ConfigDir()
	if err != nil {
		return nil, fmt.Errorf("resolve everyapi config dir: %w", err)
	}
	codexHome := filepath.Join(cfgDir, "codex-home")
	// 0700 — auth.json carries a bearer token; treat the whole
	// directory as secret. MkdirAll is a no-op when it already
	// exists with the right permissions.
	if err := os.MkdirAll(codexHome, 0o700); err != nil {
		return nil, fmt.Errorf("create codex-home: %w", err)
	}

	if err := writeCodexAuthJSON(codexHome, token); err != nil {
		return nil, err
	}
	if err := writeCodexConfigTOML(codexHome, apiBase); err != nil {
		return nil, err
	}

	return map[string]string{"CODEX_HOME": codexHome}, nil
}

// prepareCodexTransparent keeps Codex on its built-in OpenAI provider while
// forcing API-key auth with a non-secret placeholder. Connector replaces that
// placeholder only after decrypting a registered api.openai.com model route.
func prepareCodexTransparent() (map[string]string, error) {
	cfgDir, err := config.ConfigDir()
	if err != nil {
		return nil, fmt.Errorf("resolve everyapi config dir: %w", err)
	}
	codexHome := filepath.Join(cfgDir, "codex-home")
	if err := os.MkdirAll(codexHome, 0o700); err != nil {
		return nil, fmt.Errorf("create codex-home: %w", err)
	}
	if err := writeCodexAuthJSON(codexHome, transparentPlaceholderCredential); err != nil {
		return nil, err
	}
	if err := writeCodexOfficialConfigTOML(codexHome); err != nil {
		return nil, err
	}
	return map[string]string{"CODEX_HOME": codexHome}, nil
}

func writeCodexOfficialConfigTOML(codexHome string) error {
	defaults, err := readCodexUserDefaults(codexHome)
	if err != nil {
		return err
	}
	encodedDefaults, err := encodeCodexUserDefaults(defaults)
	if err != nil {
		return err
	}
	body := []byte("# Auto-generated by `everyapi use codex --transparent`.\n" +
		"# Uses Codex's built-in OpenAI provider and official API origin.\n" +
		"# Root-level model and model_reasoning_effort values are preserved.\n\n" +
		"model_provider = \"openai\"\n" + encodedDefaults)
	return writeFileAtomic(filepath.Join(codexHome, "config.toml"), body, 0o644)
}

// writeCodexAuthJSON atomically writes auth.json with apikey mode +
// the relay key. Schema mirrors what codex itself emits for the
// `codex login --api-key ...` path: OPENAI_API_KEY top-level (NOT
// nested under tokens), tokens nulled out, auth_mode pinned.
//
// 0600 perms — same as how codex writes its own auth.json.
func writeCodexAuthJSON(codexHome, token string) error {
	payload := map[string]any{
		"OPENAI_API_KEY": token,
		"tokens":         nil,
		"auth_mode":      "apikey",
	}
	body, err := json.MarshalIndent(payload, "", "  ")
	if err != nil {
		return fmt.Errorf("marshal codex auth.json: %w", err)
	}
	return writeFileAtomic(filepath.Join(codexHome, "auth.json"), body, 0o600)
}

// writeCodexConfigTOML writes config.toml selecting the everyapi
// model_provider as default. We do NOT copy the user's real
// ~/.codex/config.toml — the user explicitly chose isolation, so
// personality/theme/etc. start fresh. The EveryAPI-owned provider
// configuration is regenerated on every `everyapi use codex` launch;
// root-level model defaults are read from the existing config first.
//
// wire_api = "responses" matches the backend's native /v1/responses
// surface. requires_openai_auth = false because EveryAPI's relay key
// is its own credential, not an OpenAI ChatGPT session token.
func writeCodexConfigTOML(codexHome, apiBase string) error {
	base := joinBase(apiBase, "/v1")
	defaults, err := readCodexUserDefaults(codexHome)
	if err != nil {
		return err
	}
	encodedDefaults, err := encodeCodexUserDefaults(defaults)
	if err != nil {
		return err
	}
	// TOML built by string concat — small and shape-stable, not worth
	// dragging in a TOML writer dep just for two stanzas. base_url is
	// defensively escaped as a TOML basic string (mirroring hermes's
	// yamlDoubleQuote) so a stray quote / newline in a user-supplied
	// --api-base can't break out of the value or inject a key into the
	// [model_providers.everyapi] stanza.
	var b strings.Builder
	b.WriteString("# Auto-generated by `everyapi use codex`.\n")
	b.WriteString("# EveryAPI regenerates the provider configuration on every launch.\n")
	b.WriteString("# Root-level model and model_reasoning_effort values are preserved.\n")
	b.WriteString("\n")
	b.WriteString("model_provider = \"everyapi\"\n")
	b.WriteString(encodedDefaults)
	b.WriteString("\n")
	b.WriteString("[model_providers.everyapi]\n")
	b.WriteString("name = \"EveryAPI\"\n")
	b.WriteString("base_url = " + tomlBasicQuote(base) + "\n")
	b.WriteString("env_key = \"OPENAI_API_KEY\"\n")
	// Pin the routing surface: codex's WireApi default is Chat, which
	// would hit /v1/chat/completions. We want the gateway's native
	// /v1/responses surface (see the doc comment above).
	b.WriteString("wire_api = \"responses\"\n")
	// EveryAPI's relay key is its own credential, not an OpenAI ChatGPT
	// session token (already the codex default; written to match intent).
	b.WriteString("requires_openai_auth = false\n")
	return writeFileAtomic(filepath.Join(codexHome, "config.toml"), []byte(b.String()), 0o644)
}

func readCodexUserDefaults(codexHome string) (codexUserDefaults, error) {
	configPath := filepath.Join(codexHome, "config.toml")
	body, err := os.ReadFile(configPath)
	if err != nil {
		if os.IsNotExist(err) {
			return codexUserDefaults{}, nil
		}
		return codexUserDefaults{}, fmt.Errorf("read existing Codex config: %w", err)
	}

	var defaults codexUserDefaults
	if _, err := toml.Decode(string(body), &defaults); err != nil {
		return codexUserDefaults{}, fmt.Errorf("parse existing Codex config: %w", err)
	}
	return defaults, nil
}

func encodeCodexUserDefaults(defaults codexUserDefaults) (string, error) {
	var b strings.Builder
	config := struct {
		Model                string `toml:"model,omitempty"`
		ModelReasoningEffort string `toml:"model_reasoning_effort,omitempty"`
	}{
		Model:                defaults.Model,
		ModelReasoningEffort: defaults.ModelReasoningEffort,
	}
	if err := toml.NewEncoder(&b).Encode(config); err != nil {
		return "", fmt.Errorf("encode Codex user defaults: %w", err)
	}
	return b.String(), nil
}

// tomlBasicQuote renders s as a TOML basic string, escaping the
// characters that would otherwise terminate the string or inject
// structure. The escape forms (\\, \", \n, \r, \t) are valid in both TOML
// basic strings and YAML double-quoted scalars, so this mirrors hermes's
// yamlDoubleQuote. Sufficient for base_url; not a general TOML serializer.
func tomlBasicQuote(s string) string {
	r := strings.NewReplacer(
		`\`, `\\`,
		`"`, `\"`,
		"\n", `\n`,
		"\r", `\r`,
		"\t", `\t`,
	)
	return `"` + r.Replace(s) + `"`
}

// writeFileAtomic writes via tmp + rename so a concurrent codex read
// never sees a half-written file. tmp lives in the same directory so
// the rename is atomic (cross-FS renames degrade to copy+delete).
func writeFileAtomic(path string, data []byte, perm os.FileMode) error {
	dir := filepath.Dir(path)
	tmp, err := os.CreateTemp(dir, filepath.Base(path)+".tmp-*")
	if err != nil {
		return fmt.Errorf("create temp for %s: %w", path, err)
	}
	tmpName := tmp.Name()
	cleanup := func() { _ = os.Remove(tmpName) }
	if _, err := tmp.Write(data); err != nil {
		_ = tmp.Close()
		cleanup()
		return fmt.Errorf("write %s: %w", path, err)
	}
	if err := tmp.Chmod(perm); err != nil {
		_ = tmp.Close()
		cleanup()
		return fmt.Errorf("chmod %s: %w", path, err)
	}
	if err := tmp.Close(); err != nil {
		cleanup()
		return fmt.Errorf("close %s: %w", path, err)
	}
	if err := os.Rename(tmpName, path); err != nil {
		cleanup()
		return fmt.Errorf("rename %s: %w", path, err)
	}
	return nil
}
