package edge

import (
	"bytes"
	"fmt"
	"os"
	"path/filepath"
	"strconv"
	"strings"
	"text/template"

	"github.com/everyapi-ai/everyapi-ai/internal/i18n"
)

// composeTemplate is the canonical docker-compose.yml for an edge node.
// All three hardware profiles (nvidia / rocm / macos) collapse into
// this one template; conditionals at render time choose between an
// embedded ollama sidecar (nvidia / rocm / cpu) vs a host-native one
// reached via host.docker.internal (macos).
//
// Why generate instead of go:embed pre-written YAML:
//
//   - container_name is namespaced by node id so a single machine can
//     run multiple nodes side-by-side without compose-project clashes.
//   - env values are baked directly into the YAML; no .env file means
//     the registration token never sits next to docker-compose.yml
//     waiting to be accidentally committed.
//   - GPU passthrough is a per-mode branch — embedding three near-
//     duplicate YAMLs and picking one would be more fragile than one
//     template with a conditional.
//
// AgentImage / OllamaImage are knobs in case operator wants to pin a
// non-default (`ghcr.io/everyapi-ai/everyapi-edge:0.1.5` for a sticky
// pin, `ollama/ollama:0.1.45` to dodge a regression). Defaults match
// what clients/edge/docker-compose.yml uses by default.
const composeTemplate = `# Generated by 'everyapi edge start' — do not edit by hand.
# Re-render: ` + "`" + `everyapi edge update` + "`" + ` or delete this file and re-run start.
#
# Image: {{.AgentImage | yamlStr}} (Apache 2.0, source at
# https://github.com/everyapi-ai/everyapi-edge).
{{- if not .OllamaHostNative }}

services:
  ollama:
    image: {{.OllamaImage | yamlStr}}
    container_name: everyapi-edge-{{.NodeID}}-ollama
    restart: unless-stopped
    {{- if eq .Mode "nvidia" }}
    deploy:
      resources:
        reservations:
          devices:
            - driver: nvidia
              count: all
              capabilities: [gpu]
    {{- else if eq .Mode "rocm" }}
    devices:
      - /dev/kfd
      - /dev/dri
    group_add:
      - video
    {{- end }}
    volumes:
      - ./data/ollama:/root/.ollama
    healthcheck:
      test: ["CMD", "ollama", "list"]
      interval: 10s
      timeout: 3s
      retries: 5

  agent:
    image: {{.AgentImage | yamlStr}}
    container_name: everyapi-edge-{{.NodeID}}-agent
    restart: unless-stopped
    depends_on:
      ollama:
        condition: service_healthy
    environment:
      EVERYAPI_GATEWAY: {{.Gateway | yamlStr}}
      EVERYAPI_NODE_ID: "{{.NodeID}}"
      EVERYAPI_REGISTRATION_TOKEN: {{.RegistrationToken | yamlStr}}
      OLLAMA_URL: http://ollama:11434
      EVERYAPI_IDENTITY_PATH: /var/lib/everyapi-edge/identity.json
      EVERYAPI_NODE_NAME: {{.NodeName | yamlStr}}
      {{- if .Workloads }}
      EVERYAPI_WORKLOADS: {{.Workloads | joinComma | yamlStr}}
      {{- end }}
    volumes:
      - ./data/agent:/var/lib/everyapi-edge
{{- else }}

# macOS variant: ollama runs natively on the host (Metal acceleration
# isn't available through docker), so this compose file only carries
# the agent. Make sure 'brew install ollama && brew services start
# ollama' is done before 'everyapi edge start'.
services:
  agent:
    image: {{.AgentImage | yamlStr}}
    container_name: everyapi-edge-{{.NodeID}}-agent
    restart: unless-stopped
    extra_hosts:
      - "host.docker.internal:host-gateway"
    environment:
      EVERYAPI_GATEWAY: {{.Gateway | yamlStr}}
      EVERYAPI_NODE_ID: "{{.NodeID}}"
      EVERYAPI_REGISTRATION_TOKEN: {{.RegistrationToken | yamlStr}}
      OLLAMA_URL: http://host.docker.internal:11434
      EVERYAPI_IDENTITY_PATH: /var/lib/everyapi-edge/identity.json
      EVERYAPI_NODE_NAME: {{.NodeName | yamlStr}}
      EVERYAPI_GPU_MODEL: "Apple Silicon"
      EVERYAPI_PLATFORM: "darwin/arm64"
      {{- if .MemoryGB }}
      EVERYAPI_VRAM_GB: "{{.MemoryGB}}"
      {{- end }}
      {{- if .Workloads }}
      EVERYAPI_WORKLOADS: {{.Workloads | joinComma | yamlStr}}
      {{- end }}
    volumes:
      - ./data/agent:/var/lib/everyapi-edge
{{- end }}
`

// composeData carries the template knobs. Public-cased fields are
// what the template references.
type composeData struct {
	NodeID            int
	NodeName          string
	Mode              Mode
	Gateway           string
	RegistrationToken string
	AgentImage        string
	OllamaImage       string
	OllamaHostNative  bool // true for macOS — no ollama service in compose
	MemoryGB          int  // Apple Silicon unified host memory; zero omits the hint
	// Workloads is the capability declaration persisted at register
	// time. Rendered as EVERYAPI_WORKLOADS so the agent reports the
	// same set the seller declared (used by the gateway only as a
	// backfill for rows that predate the workloads column).
	Workloads []string
}

// renderCompose returns the YAML bytes for the given node + mode. The
// macOS branch sets OllamaHostNative; everything else uses the
// embedded sidecar with mode-specific GPU passthrough.
func renderCompose(d composeData) ([]byte, error) {
	if d.AgentImage == "" {
		d.AgentImage = "ghcr.io/everyapi-ai/everyapi-edge:latest"
	}
	if d.OllamaImage == "" {
		switch d.Mode {
		case ModeROCm:
			d.OllamaImage = "ollama/ollama:rocm"
		default:
			d.OllamaImage = "ollama/ollama:latest"
		}
	}
	if d.Mode == ModeMacOS {
		d.OllamaHostNative = true
	}

	// yamlStr quotes a string as a JSON-style double-quoted YAML
	// scalar — valid YAML by construction, and the only escape
	// sequences are \\ and \" which YAML resolves the same way as
	// JSON. Used for every user/operator/network-sourced scalar —
	// NodeName, RegistrationToken, and the operator-supplied
	// AgentImage / OllamaImage tags — so a stray `:` / `#` / newline
	// can't desync the YAML or smuggle in a service key (e.g.
	// `privileged: true`).
	//
	// Compose ALSO runs $VAR / ${VAR} interpolation over compose-file
	// values at `pull`/`up` time, independent of YAML quoting — the only
	// literal-$ escape is `$$`. strconv.Quote does not double `$`, so a
	// value like `gpu-${HOME}` would be silently substituted from the
	// operator's shell env (leaking host state or emptying the field).
	// Double every `$` after quoting to neutralize the interpolation.
	funcs := template.FuncMap{
		"yamlStr": func(s string) string {
			return strings.ReplaceAll(strconv.Quote(s), "$", "$$")
		},
		"joinComma": func(parts []string) string {
			return strings.Join(parts, ",")
		},
	}
	tmpl, err := template.New("compose").Funcs(funcs).Parse(composeTemplate)
	if err != nil {
		return nil, err
	}
	var buf bytes.Buffer
	if err := tmpl.Execute(&buf, d); err != nil {
		return nil, err
	}
	return buf.Bytes(), nil
}

// writeCompose renders + writes docker-compose.yml into the node's
// workdir, creating parent dirs as needed.
func writeCompose(dir string, d composeData) (string, error) {
	if err := os.MkdirAll(filepath.Join(dir, "data"), 0o755); err != nil {
		return "", err
	}
	out, err := renderCompose(d)
	if err != nil {
		return "", err
	}
	path := filepath.Join(dir, "docker-compose.yml")
	if err := os.WriteFile(path, out, 0o600); err != nil {
		return "", fmt.Errorf(i18n.T("edge.compose.write_failed"), err)
	}
	return path, nil
}
